# AdBrain Chrome watchdog. Do NOT edit manually - regenerated by the installer.
# Runs every 5 minutes via a scheduled task.
#
# Behavior:
#   1. Pings the manager's /api/health endpoint (2s timeout).
#      * If manager is DOWN or unreachable: exit silently WITHOUT launching
#        Chrome. This keeps the worker PC quiet + resource-idle whenever the
#        manager is off (no point running Chrome if nothing can pull work).
#      * If manager is UP: continue to step 2.
#   2. If AdBrain Chrome (identified by --user-data-dir matching our isolated
#      profile) is already running: exit silently.
#   3. Otherwise: launch Chrome minimized with the AdBrain profile + extension.
#
# Placeholders __PROFILE__ / __EXTDIR__ / __CHROME__ / __LOG__ / __MGR__ are
# substituted by the installer at install-time.

$ErrorActionPreference = 'SilentlyContinue'
$profileDir = '__PROFILE__'
$extDir     = '__EXTDIR__'
$chromeExe  = '__CHROME__'
$logFile    = '__LOG__'
$managerUrl = '__MGR__'

function Add-Log($msg) {
    Add-Content -Path $logFile -Value ((Get-Date).ToString('s') + '  ' + $msg)
}

# 1) Manager reachability check. Skip Chrome relaunch if manager is off.
try {
    $req = [System.Net.WebRequest]::Create($managerUrl + '/api/health')
    $req.Method = 'GET'
    $req.Timeout = 2000
    $resp = $req.GetResponse()
    $code = [int]$resp.StatusCode
    $resp.Close()
    if ($code -ne 200) {
        Add-Log ('[skip] manager returned HTTP ' + $code + ' - not launching Chrome')
        exit 0
    }
} catch {
    # Silent exit on unreachable manager - this is the whole point.
    # Uncomment the next line if you want a log entry per failed ping:
    # Add-Log ('[skip] manager unreachable: ' + $_.Exception.Message)
    exit 0
}

# 2) AdBrain Chrome already running? Then nothing to do.
try {
    $needle = '--user-data-dir=' + $profileDir
    $running = @(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" |
                 Where-Object { $_.CommandLine -and ($_.CommandLine.Contains($needle)) }).Count -gt 0
    if ($running) {
        # Already up - nothing to do. (No log entry to keep noise down.)
        exit 0
    }

    # 3) Not running - launch it.
    $launchArgs = '--user-data-dir="' + $profileDir + '" --load-extension="' + $extDir + '" --new-window "chrome://newtab"'
    Start-Process -FilePath $chromeExe -ArgumentList $launchArgs -WindowStyle Minimized
    Add-Log ('[relaunched] ' + $chromeExe)
} catch {
    Add-Log ('[error] ' + $_.Exception.Message)
}
