# AdBrain Chrome watchdog. Do NOT edit manually - regenerated by the installer.
# Runs every 5 minutes via a scheduled task.
#
# Behavior:
#   1. Pings the manager's /api/health endpoint (2s timeout).
#      * If manager is DOWN or unreachable: exit silently WITHOUT launching
#        Chrome. This keeps the worker PC quiet + resource-idle whenever the
#        manager is off (no point running Chrome if nothing can pull work).
#      * If manager is UP: continue to step 2.
#   2. NEW: Compare local bundle-hash to manager's /api/worker/version-hash.
#      If different, download the current WORKER_FILES from the manager,
#      overwrite our local extension dir, save the new hash, then POST a
#      broadcast 'hard_reset' command to the manager's command bus. Every
#      running worker picks up hard_reset within ~30s and self-reloads,
#      loading the freshly-updated files. Skips silently if either
#      endpoint is unreachable OR if we're on the same hash already.
#   3. If AdBrain Chrome (identified by --user-data-dir matching our isolated
#      profile) is already running: exit silently (after any update above).
#   4. Otherwise: launch Chrome minimized with the AdBrain profile + extension.
#
# Placeholders __PROFILE__ / __EXTDIR__ / __CHROME__ / __LOG__ / __MGR__
# / __TOKEN__ are substituted by the installer at install-time.

$ErrorActionPreference = 'SilentlyContinue'
$profileDir = '__PROFILE__'
$extDir     = '__EXTDIR__'
$chromeExe  = '__CHROME__'
$logFile    = '__LOG__'
$managerUrl = '__MGR__'
$token      = '__TOKEN__'    # optional; empty = no header sent

function Add-Log($msg) {
    Add-Content -Path $logFile -Value ((Get-Date).ToString('s') + '  ' + $msg)
}

function Mgr-Get($path) {
    # Returns response text on 200, $null on any failure. Uses raw
    # WebRequest so we don't need Invoke-WebRequest's cmdlet baggage.
    try {
        $req = [System.Net.WebRequest]::Create($managerUrl + $path)
        $req.Method = 'GET'
        $req.Timeout = 4000
        if ($token) { $req.Headers.Add('X-Manager-Token', $token) }
        $resp = $req.GetResponse()
        $sr = New-Object System.IO.StreamReader($resp.GetResponseStream())
        $body = $sr.ReadToEnd()
        $sr.Close(); $resp.Close()
        return $body
    } catch { return $null }
}

function Mgr-Post($path, $bodyText) {
    try {
        $req = [System.Net.WebRequest]::Create($managerUrl + $path)
        $req.Method = 'POST'
        $req.ContentType = 'application/json'
        $req.Timeout = 4000
        if ($token) { $req.Headers.Add('X-Manager-Token', $token) }
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($bodyText)
        $req.ContentLength = $bytes.Length
        $s = $req.GetRequestStream(); $s.Write($bytes, 0, $bytes.Length); $s.Close()
        $resp = $req.GetResponse(); $resp.Close()
        return $true
    } catch { return $false }
}

function Download-To($url, $destPath) {
    try {
        $req = [System.Net.WebRequest]::Create($managerUrl + $url)
        $req.Method = 'GET'
        $req.Timeout = 15000
        $resp = $req.GetResponse()
        $stream = $resp.GetResponseStream()
        $destDir = Split-Path -Parent $destPath
        if ($destDir -and -not (Test-Path $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }
        $fs = [System.IO.File]::Create($destPath)
        $stream.CopyTo($fs)
        $fs.Close(); $stream.Close(); $resp.Close()
        return $true
    } catch { return $false }
}

# 1) Manager reachability check. Skip Chrome relaunch if manager is off.
# Go through Mgr-Get so the auth header is attached. This probe used to
# build its own WebRequest and send NO token; /api/health is token-gated,
# so on any manager with MANAGER_TOKEN set it answered 401, GetResponse()
# threw, and the catch below exited 0 — silently, every run. The watchdog
# therefore never reached the auto-update or the Chrome relaunch, and
# workers sat on stale code indefinitely with nothing in the log to show
# for it.
$healthBody = Mgr-Get '/api/health'
if (-not $healthBody) {
    # Manager down, unreachable, or rejecting our token. Staying quiet here
    # is deliberate: no point running Chrome if nothing can hand out work.
    exit 0
}

# 2) Auto-update check. Compares local bundle hash to manager's; if
# different, downloads new files + broadcasts hard_reset so running
# workers pick up the update within ~30s. Fully silent on no-change
# (which is the common case).
try {
    $hashFile = Join-Path $profileDir '.adbrain-bundle-hash'
    $localHash = ''
    if (Test-Path $hashFile) { $localHash = (Get-Content $hashFile -Raw).Trim() }
    $remoteBody = Mgr-Get '/api/worker/version-hash'
    if ($remoteBody) {
        $remote = $remoteBody | ConvertFrom-Json
        $remoteHash = $remote.hash
        if ($remoteHash -and $remoteHash -ne $localHash) {
            Add-Log ('[update] local=' + $localHash.Substring(0, [Math]::Min(8, $localHash.Length)) + ' remote=' + $remoteHash.Substring(0, [Math]::Min(8, $remoteHash.Length)) + ' - downloading ' + $remote.file_count + ' file(s)')
            $filesBody = Mgr-Get '/worker-files.json'
            if ($filesBody) {
                $files = ($filesBody | ConvertFrom-Json).files
                $okCount = 0; $failCount = 0
                foreach ($rel in $files) {
                    $dest = Join-Path $extDir $rel
                    if (Download-To ('/worker/' + $rel) $dest) { $okCount++ } else { $failCount++ }
                }
                if ($failCount -eq 0) {
                    Set-Content -Path $hashFile -Value $remoteHash -Encoding utf8
                    # Make every running worker pick up the new files.
                    # Workers reload via chrome.runtime.reload(), which
                    # re-reads the JS from the (now-updated) extension dir.
                    # State (workerId, buffered pushes, claimed jobs) all
                    # survives via chrome.storage.
                    #
                    # This used to post a bare graceful_reload, despite the
                    # comment claiming hard_reset. A worker with a SKU in
                    # flight DEFERS a graceful reload until that SKU
                    # finishes, and a SKU stuck in a KP retry loop runs for
                    # ten minutes or more — so freshly downloaded files sat
                    # on disk while the old code kept running, indefinitely.
                    # /api/commands/update-all sends graceful_reload now and
                    # escalates to hard_reset on the MANAGER after 30s, so
                    # the update always lands.
                    $cmdBody = '{"createdBy":"watchdog-auto-update"}'
                    if (Mgr-Post '/api/commands/update-all' $cmdBody) {
                        Add-Log ('[update] ' + $okCount + ' file(s) written; graceful_reload sent, hard_reset escalation armed - workers reload within ~60s')
                    } else {
                        Add-Log ('[update] ' + $okCount + ' file(s) written but hard_reset POST failed; workers need manual reload')
                    }
                } else {
                    Add-Log ('[update] download failed: ' + $failCount + ' of ' + $files.Count + ' files errored - not switching hash')
                }
            }
        }
    }
} catch {
    Add-Log ('[update] auto-update check failed: ' + $_.Exception.Message)
}

# 2b) Self-update.
#
# The watchdog could not previously update itself: it runs from $root while
# auto-update only writes into $extDir, and the template was not in
# WORKER_FILES. So any bug in THIS script was permanent until someone re-ran
# the installer by hand on every worker PC — which is exactly what happened
# with the unauthenticated health probe: it exited 0 silently for hours on
# every machine, and no amount of pushing from the manager could fix it.
#
# Now: fetch the current template, substitute the same placeholders the
# installer does (using the values already baked into THIS file), and
# rewrite ourselves if the result differs. Next scheduled run picks it up.
try {
    $tplBody = Mgr-Get '/worker/chrome-watchdog-template.ps1'
    if ($tplBody) {
        # Build the placeholder tokens at RUNTIME rather than writing them as
        # literals. The installer does a global find-and-replace over this
        # whole file, so a literal placeholder here would itself be
        # substituted at install time and this code would then be replacing
        # the wrong string. That is exactly how the token guard broke: it
        # compared $token against the token placeholder, the installer
        # rewrote that placeholder too, and the check became "send the token
        # only if it differs from itself" — never true, so nothing was ever
        # authenticated. This comment avoids spelling the placeholders out
        # for the same reason.
        $u = '__'
        # .Replace() is LITERAL. PowerShell's -replace is regex, and these
        # values are Windows paths full of backslashes, which regex would
        # mangle into escape sequences.
        $rendered = $tplBody
        $rendered = $rendered.Replace(($u + 'PROFILE' + $u), $profileDir)
        $rendered = $rendered.Replace(($u + 'EXTDIR'  + $u), $extDir)
        $rendered = $rendered.Replace(($u + 'CHROME'  + $u), $chromeExe)
        $rendered = $rendered.Replace(($u + 'LOG'     + $u), $logFile)
        $rendered = $rendered.Replace(($u + 'MGR'     + $u), $managerUrl)
        $rendered = $rendered.Replace(($u + 'TOKEN'   + $u), $token)
        $selfPath = $MyInvocation.MyCommand.Path
        $current  = ''
        if ($selfPath -and (Test-Path $selfPath)) { $current = Get-Content $selfPath -Raw }
        # Compare NORMALISED text, not raw bytes.
        #
        # A raw comparison never matched and the watchdog rewrote itself on
        # every single run — the log filled with "[self-update] watchdog
        # script updated" every two minutes forever. Three reasons, any one
        # of which is enough: the manager serves LF while Set-Content writes
        # CRLF, Set-Content -Encoding utf8 prepends a BOM on Windows
        # PowerShell 5.1, and Get-Content -Raw keeps a trailing newline the
        # rendered string does not have. Normalising line endings, BOM and
        # trailing whitespace compares what actually matters: the script.
        # [string] cast on the BOM is required: Replace([char], '') binds to
        # the Replace(char, char) overload and throws, because '' is not a
        # char. That silently sent the comparison down the error path.
        $bom = [string][char]0xFEFF
        $norm = { param($t) if ($null -eq $t) { '' } else { $t.Replace($bom, '').Replace("`r`n", "`n").TrimEnd() } }
        if ($selfPath -and $rendered.Length -gt 500 -and (& $norm $rendered) -ne (& $norm $current)) {
            Set-Content -Path $selfPath -Value $rendered -Encoding utf8
            Add-Log '[self-update] watchdog script updated from the manager; next run uses the new version'
        }
    }
} catch {
    Add-Log ('[self-update] failed (non-fatal): ' + $_.Exception.Message)
}

# 3) AdBrain Chrome already running? Then nothing to do.
try {
    $needle = '--user-data-dir=' + $profileDir
    $running = @(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" |
                 Where-Object { $_.CommandLine -and ($_.CommandLine.Contains($needle)) }).Count -gt 0
    if ($running) {
        # Already up - nothing to do. (No log entry to keep noise down.)
        exit 0
    }

    # 4) Not running - launch it.
    $launchArgs = '--user-data-dir="' + $profileDir + '" --load-extension="' + $extDir + '" --new-window "chrome://newtab"'
    Start-Process -FilePath $chromeExe -ArgumentList $launchArgs -WindowStyle Minimized
    Add-Log ('[relaunched] ' + $chromeExe)
} catch {
    Add-Log ('[error] ' + $_.Exception.Message)
}
